name: asynchronous_validator
version: 1.0.2
authors:
- Karan Goel <karan@goel.io>
- Naufal Fachrian <naufalfachrian@gmail.com>
description: String validation and sanitization for Dart.
homepage: https://github.com/naufalfachrian/dart-asynchronous-validator
documentation: https://github.com/naufalfachrian/dart-asynchronous-validator
environment:
  sdk: '>=2.0.0 <3.0.0'
